---
version: '2'
services:
  redis:
    image: redis
    ports:
      - "6380:6380"
    volumes:
      - /mnt/data/aws/redis:/data/
  database:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - /mnt/data/aws/mongodb:/data/db

