#
###################################
# Site wide configuration
####################################
#
title: Bryan Kroger ( krogebry )
email: bryan.kroger@gmail.com
description: Building teams.
url: https://krogebry.github.io/
keywords: ["Ruby", "Linux", "DevOps", "Interviews", "Teams", "SRE", "Site Reliability Engineering", "Automation"]
future: false

#
###################################
# Jekyll configuration
####################################
#
timezone:           America/Chicago
markdown:           kramdown
highlighter:        rouge
excerpt_separator:  <!--more-->
permalink:          /articles/:year-:month/:title
paginate:           5
paginate_path:      /page:num/
page:
  comments: true

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false

sass:
  sass_dir: _sass
  style: :compressed

#
###################################
# Site Owner configuration
####################################
#
owner:
  name: Bryan Kroger
  avatar: profile.jpg
  job: "SRE Team Builder"
  bio: "Helping teams find better outcomes."
  email: bryan.kroger@gmail.com
  disqus-shortname: krogebry
  twitter: krogebry
  facebook: bryan.kroger
  google:
    plus: #username
    analytics: UA-123-1
    verify:
    ad-client:
    ad-slot:
  bing-verify:
  github: krogebry #username
  # stackoverflow: 123/krogebry
  linkedin: bryankroger #username
  xing: #username
  instagram: code_n_combovers #username
  lastfm: #username
  tumblr: #username
  pinterest: #username
  foursquare: #username
  steam: #username
  dribbble: #username
  youtube: #username
  soundcloud: #username
  weibo: #username
  flickr: #username
  codepen: #username
  telegram: #username

webrick:
  headers:
    Access-Control-Allow-Origin: "*"