source 'https://supermarket.chef.io'

cookbook 'gocd'
cookbook 'sensu'
cookbook 'hashicorp-vault', '~> 2.4.0'
cookbook 'nginx', '~> 7.0.0'
cookbook 'chef-client'
cookbook 'docker'
cookbook 'elkstack', '~> 6.0.4'
