source 'https://supermarket.chef.io'

cookbook 'gocd'
cookbook 'sensu'
#cookbook 'vault'
cookbook 'hashicorp-vault', '~> 2.4.0'
cookbook 'nginx'

cookbook 'chef-client'

cookbook 'docker'

#cookbook 'kibana', '~> 0.2.1'
#cookbook 'logstash', '~> 0.12.0'
#cookbook 'chef_nginx', '~> 4.0.1'
#cookbook 'elasticsearch', '~> 3.0.0'
cookbook 'elkstack', '~> 6.0.4'

